vim.keymap.set("n", "<Leader>r", ":MagmaEvaluateOperator<CR>", {silent = true, expr = true})
vim.keymap.set("n", "<Leader>rr", ":MagmaEvaluateLine<CR>", {silent = true})
vim.keymap.set("x", "<Leader>r ", ":<C-u>MagmaEvaluateVisual<CR>", {silent = true})
vim.keymap.set("n", "<Leader>rc", ":MagmaReevaluateCell<CR>", {silent = true})
vim.keymap.set("n", "<Leader>rd", ":MagmaDelete<CR>", {silent = true})
vim.keymap.set("n", "<Leader>ro", ":MagmaShowOutput<CR>", {silent = true})
vim.keymap.set("n", "<Leader>eo", ":noautocmd MagmaEnterOutput<CR>", {silent = true})

vim.cmd('let g:magma_automatically_open_output = v:false')
vim.cmd('let g:magma_wrap_output = v:false')
vim.cmd('let g:magma_image_provider = "ueberzug"')
